version: "3.9"
services:
    postgres:
        image: postgres:10-alpine
        container_name: postgresql_db
        environment:
            - POSTGRES_DB=stakefish
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: always
        ports:
            - "35432:5432"
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://postgres:postgres@localhost:5432/stakefish
            NODE_ENV: development
            PORT: 5000
        ports:
            - "5000:5000"
        command: npm run start:dev 
  


